#include "TM4C123.h" 
#include <string.h>
#include "LCD2x16.h" 


int main()
{
	SYSCTL->RCGCGPIO =0x01;
	SYSCTL->RCGCGPIO |=0x02;
	GPIOA->DIR |=0xE0;
	GPIOA->DEN |=0xE0;
	GPIOB->DIR |=0xFF;
	GPIOB->DEN |=0xFF;
	
	__DATA_R GPIO_DATA;
	__CTRL_R GPIO_CTRL;
	GPIO_CTRL.E=0;GPIO_CTRL.RS=0;GPIO_CTRL.RW=0;
	
	GPIO_DATA.D7 = (GPIOB->DATA & 0x80)>>7;
	GPIO_DATA.D6 = (GPIOB->DATA & 0x40)>>6;
	GPIO_DATA.D5 = (GPIOB->DATA & 0x20)>>5;
	GPIO_DATA.D4 = (GPIOB->DATA & 0x10)>>4;
	GPIO_DATA.D3 = (GPIOB->DATA & 0x08)>>3;
	GPIO_DATA.D2 = (GPIOB->DATA & 0x04)>>2;
	GPIO_DATA.D1 = (GPIOB->DATA & 0x02)>>1;
	GPIO_DATA.D0 = (GPIOB->DATA & 0x01)>>0;
	

	
	
	LCD_DISP(0, &GPIO_DATA, &GPIO_CTRL,'z' );
	
	GPIOA->DATA |= GPIO_CTRL.E  <<7;
	GPIOA->DATA |= GPIO_CTRL.RW <<6;
	GPIOA->DATA |= GPIO_CTRL.RS <<5;
}
